openapi: 3.0.0
info:
  version: 1.0.0
  title: YamlResolver API
paths:
  /login:
    post:
      summary: Authentication endpoint
      operationId: login
      tags:
        - auth
      responses:
        '200':
          description: User information and login token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAuth'
  '/user/{user_id}':
    get:
      summary: Returns the specified user
      operationId: getUser
      tags:
        - users
      responses:
        '200':
          description: User information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /posts:
    get:
      summary: Returns a list of posts
      operationId: getPosts
      tags:
        - posts
      responses:
        '200':
          description: A list of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
components:
  UserAuth:
    properties:
      user:
        $ref: '#/components/schemas/User'
      token:
        type: string
  User:
    properties:
      id:
        type: string
      email:
        type: string
        format: email
      first_name:
        type: string
      last_name:
        type: string
  Post:
    properties:
      id:
        type: string
      title:
        type: string
      created_at:
        type: string
        format: date-time
